language: R
cache: packages
pandoc_version: 2.3.1

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libxml2
      - cargo

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github-token: $GITHUB_PAT  # Set in the settings page 
  on:
    branch: master